services:
  price-bot:
    build:
      context: ../../vendaOnline
      dockerfile: ../Docker/sqlite-bot/Dockerfile
    container_name: price-bot
    volumes:
      - ./db:/database
    ports:
      - "3000:3000"
    env_file:
      - ../../vendaOnline/.env
    restart: unless-stopped
